---
AWSTemplateFormatVersion: "2010-09-09"
Description: "GitHub Actions bucket for when GitHub wants to communicate with AWS."
Resources:
  originAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ghu2023-demo
        SigningProtocol: sigv4
        SigningBehavior: always
        OriginAccessControlOriginType: s3

  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: ghu2023-demo
          ViewerProtocolPolicy: redirect-to-https
        IPV6Enabled: true
        Origins:
          S3OriginConfig
          OriginAccessControl:
            OriginAccessId: !Ref originAccessControl
      Tags:
        - Key: key
          Value: value

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: ghu2023-demo
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: AllowGitHub2GitHub
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::ghu2023-demo
              - arn:aws:s3:::ghu2023-demo/*
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/GitHub_Actions_Role"
          - Sid: OAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::ghu2023-demo
              - arn:aws:s3:::ghu2023-demo/*
            Condition:
              StringEquals:
                AWS:SourceArn:
                  - !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/<CloudFront distribution ID>